import React from 'react';

const COMPONENT_NAME = () => {
  return (
    <div className="p-4 rounded-lg border bg-card">
      <h2 className="text-lg font-semibold">COMPONENT_NAME</h2>
      <p className="text-muted-foreground">
        This is a basic COMPONENT_NAME component generated by Elixir UI CLI.
      </p>
    </div>
  );
};

export { COMPONENT_NAME };
